defaults:
  - base_config
  - log: log
  - eval: eval
  - model: mixedprior
  - dataset: PMtranslated75

dataset:
  dir_data_base: "data/data"
  dir_clfs_base: "data/trained_classifiers"

model:
  temp_annealing: "cosine"  

log:
  wandb_offline: True